Add error_exit function

diff --git a/MGEcatcher b/MGEcatcher
--- a/MGEcatcher
+++ b/MGEcatcher
@@ -1,6 +1,15 @@
 #!/bin/bash
 
 set -e
+
+# error function
+error_exit() {
+        msg=$1
+        exit_code=${2:-1}
+        echo -e "\033[1;31m${msg}\033[0m"
+        usage
+}
+
 check_deps() {
     for app in $CONDA_PREFIX/bin/blastn $CONDA_PREFIX/bin/bedtools; do
         command -v $app >/dev/null 2>&1 || error_exit "$0\nERROR: Cannot find \
@@ -8,7 +17,7 @@ check_deps() {
     done
 }
 
-VERSION=0.1.0
+VERSION=0.2
 check_deps
 usage() {
 USAGE="
@@ -20,14 +29,21 @@ Automated pipeline to identify mobile genetic elements in
 =========================================================
 by Vinícius H Franceschini Santos, 2020
 
-Usage: MGEcatcher -r <reads.fq> -m <mge.fa> -t <N> \\
-                      -o <output.txt> -b <BC01>
+\e[4mUsage\e[0m:
 
-   -r          fastq file for basecalled reads to be used as subject
-   -m          fasta file containing MGE sequences to be used as query
-   -o          output filename
-   -b          barcode identifier (ex.: BC01)
-   -t          number of threads (default: 10)
+MGEcatcher --reads <reads.fq> --mge_seq <mge.fa> [--threads <N>] \\
+           --output <path/to/output/> --barcode <BC01>
+
+\e[4mRequired arguments\e[0m:
+
+   --reads        Fastq file for basecalled reads to be used as subject
+   --mge_seq      Fasta file containing MGE sequences to be used as query
+   --output       Output dir name; will be created if does not exist
+   --barcode      Barcode identifier (ex.: BC01)
+
+\e[4mOptional arguments\e[0m:
+
+   --threads      Number of threads (default: 10)
 
 "
 printf "%s\\n" "$USAGE"
@@ -50,10 +66,17 @@ DONEmsg() {
 # parse args
 
 THREADS=10
+# option strings
+SHORT=h
+LONG=help,reads:,barcode:,mge_seq:,output:,threads:
 
-while getopts "hr:t:m:o:f:b:" OPT; do
-    case $OPT in
-    h)
+# read the options
+OPTS=$(getopt --options $SHORT --long $LONG --name "$0" -- "$@")
+if [ $? != 0 ] ; then echo "Failed to parse options...exiting." ; exit 1 ; fi
+eval set -- "$OPTS"
+while true ; do
+  case "$1" in
+    -h | --help )
       usage
       ;;
     r)
